# Generated by Django 5.0.2 on 2024-02-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapcartAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
